name: Provision Azure Infrastructure

on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Provision with Bicep
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          scope: subscription
          region: eastus
          template: ./infrastructure/bicep/main.bicep
          parameters: |
            location=eastus
            resourceGroupName=ai-multiagent-lab-rg

      - name: Provision with Terraform
        if: false # Disable Terraform for now
        run: |
          cd infrastructure/terraform
          terraform init
          terraform apply -auto-approve


